### ISSUE TITLE
error in line 82 and line 143

### ISSUE THREAD

**Issue by Ibrahimshaikh1258** [mailrocketsystems/AIComputerVision#10]
![IBRAHIM](https://user-images.githubusercontent.com/100829273/160583391-04f58c9b-da15-429c-b63b-8aa61da1e7b7.png)

**Comment by Ibrahimshaikh1258** [comment]
Traceback (most recent call last):
  File "C:\Users\Desktop101\PycharmProjects\hifi\person counting.py", line 143, in <module>
    main()
  File "C:\Users\Desktop101\PycharmProjects\hifi\person counting.py", line 82, in main
    person_detections = detector.forward()
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:1166: error: (-213:The function/feature is not implemented) Unknown backend identifier in function 'cv::dnn::dnn4_v20211220::wrapMat'
