### ISSUE TITLE
sometimes program gives this error! 

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [mailrocketsystems/AIComputerVision#2]
s TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "face_mask_detector.py", line 23, in <module>
    frame = imutils.resize(frame, width=400)
  File "C:\Users\PSH4\AppData\Local\Programs\Python\Python37\lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Can you tell why is it happening? also tell me your opencv version
Thanks

**Comment by abhinavrawat27** [comment]
This error says that its not able to load the frames from video file or your webcam. Make sure you have given proper path to the video file or webcam. Thanks
